language: python

python:
  - 2.7
  - 3.5

install:
  - pip install -U pip setuptools
  - pip install Cython
  - pip install gevent

before_script:
  - python setup.py install

script:
  - cd tests/http_head
  - python fake_slow_http_server.py&
  - pid=$!
  - python setup.py build_ext --inplace
  - python test.py
  - kill $pid

branches:
  except:
    - legacy
