language: python
python: 3.5
services: docker
sudo: required
cache:
  bundler: true
  directories:
      - $HOME/.cache/pip
      - $HOME/docker
env:
  - TOX_ENV=py35 PYENV=cp35
    DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - TOX_ENV=py27 PYENV=cp27
    DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - docker pull $DOCKER_IMAGE
  - pip install -U pip setuptools
  - pip install Cython tox
script:
  - tox -e $TOX_ENV && docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/.travis/build-wheels.sh greenify $PYENV
before_cache:
  - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
deploy:
  provider: pypi
  user: windreamer
  password:
    secure: RITBiQqqC2dxKzFfhYeVkr9ZQGIaHV+sQifZKCAfNcbBKoh10ea37ZyF5JiGxeHf7v+gtPOa9ksO8PNwmZADLUln+qC1vO4LgSWB8P1GPPYabIKDDJB3Rvzv/cDDOlNPzcdIMb0L4STDFlI2NS5Q+STF0rJp0g0YrzrVCinBfSY=
  on:
    tags: true
    repo: douban/greenify
